services:

  redis:
    image: redis:7.2-rc3-alpine3.18
    container_name: extauthz-rust.redis
    command: >
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_PORT}
    networks:
      - redis_net

  extauthz:
    build:
      context: ./extauthz
      args:
        - PACKAGE_NAME=extauthz
        - SERVER_PORT=${EXT_AUTHZ_PORT}
        - RELEASE_BUILD=${RELEASE_BUILD}
    image: ${DOCKER_REGISTRY}/extauthz-rust.extauthz:latest
    container_name: extauthz-rust.extauthz
    environment:
      - SERVER_PORT=${EXT_AUTHZ_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis:${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - redis_net
      - extauthz_net

  nginx:
    build:
      context: ./nginx
      args:
        - SERVER_PORT=${NGINX_SERVER_PORT}
    image: ${DOCKER_REGISTRY}/extauthz-rust.nginx:latest
    container_name: extauthz-rust.nginx
    environment:
      - SERVER_PORT=${NGINX_SERVER_PORT}
      - SERVER_NAME=${NGINX_SERVER_NAME}
    networks:
      - nginx_net

  envoy:
    build:
      context: ./envoy
      args:
        - SERVER_PORT=${ENVOY_SERVER_PORT}
        - ADMIN_PORT=${ENVOY_ADMIN_PORT}
    image: ${DOCKER_REGISTRY}/extauthz-rust.envoy:latest
    container_name: extauthz-rust.envoy
    ports:
      - "${ENVOY_EXTERNAL_PORT}:${ENVOY_SERVER_PORT}"
    environment:
      - SERVER_PORT=${ENVOY_SERVER_PORT}
      - ADMIN_PORT=${ENVOY_ADMIN_PORT}
      - NGINX_SERVER_PORT=${NGINX_SERVER_PORT}
      - NGINX_SERVER_ADDRESS=nginx
      - EXT_AUTHZ_SERVER_PORT=${EXT_AUTHZ_PORT}
      - EXT_AUTHZ_SERVER_ADDRESS=extauthz
    depends_on:
      - extauthz
      - nginx
    networks:
      - extauthz_net
      - nginx_net
      - internet

networks:
  redis_net:
    driver: bridge
    internal: true
  extauthz_net:
    driver: bridge
    internal: true
  nginx_net:
    driver: bridge
    internal: true
  internet:
    driver: bridge